name: frontend
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  custom_navigation_bar: ^0.8.2
  dio: ^5.1.2
  ficonsax: ^0.0.3
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^5.0.11
  flutter_hooks: ^0.18.6
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.8.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.1.1
  get: ^5.0.0-release-candidate-4
  get_storage: ^2.1.1
  google_sign_in: ^6.1.0
  graphql_flutter: ^5.2.0-beta.1
  timeago_flutter: ^3.4.0
  timeago: ^3.4.0
  image_picker: ^0.8.7+5
  infinite_scroll_pagination: ^4.0.0-dev.1
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  shimmer: ^3.0.0
  slide_countdown: ^0.6.0-dev.2
  smooth_page_indicator: ^1.1.0
  flutter_staggered_grid_view: ^0.6.2
  url_launcher: ^6.1.11
  flutter_link_previewer: ^3.2.2
   # Map Packages
  map_launcher: ^2.5.0+1
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_map_marker_cluster:
    git:
      url: https://github.com/nploi/flutter_map_marker_cluster
      ref: upgrade_flutter_map_v4
  flutter_map_tile_caching: ^8.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/brand/
    - assets/avatars/
    - assets/circle_avatars/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
