name: frontend
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  flutter_remix: ^0.0.3
  flutter_screenutil: ^5.8.1
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  flutter_zoom_drawer: ^3.0.4+1
  get: ^5.0.0-release-candidate-4
  get_storage: ^2.1.1
  google_sign_in: ^6.1.0
  graphql_flutter: ^5.2.0-beta.1
  image_picker: ^0.8.7+5
  jwt_decoder: ^2.0.1
  loading_animation_widget: ^1.2.0+4
  pinput: ^2.2.31
  slide_countdown: ^0.6.0-dev.2
  smooth_page_indicator: ^1.1.0

  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/brand/
    - assets/avatars/
    - assets/circle_avatars/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
